// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhDYskN01ZZM3fJ1zRlElDfI54XHXpHY',
    appId: '1:464819707457:ios:782434f2254dd3ba2630c0',
    messagingSenderId: '464819707457',
    projectId: 'realtbox-94ff0',
    storageBucket: 'realtbox-94ff0.appspot.com',
    iosBundleId: 'in.axivise.realtbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaDnjwNfGuLGmTHx0jnf3ayeyJod6v60g',
    appId: '1:464819707457:web:a68fdd88c246fc3a2630c0',
    messagingSenderId: '464819707457',
    projectId: 'realtbox-94ff0',
    authDomain: 'realtbox-94ff0.firebaseapp.com',
    storageBucket: 'realtbox-94ff0.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaDnjwNfGuLGmTHx0jnf3ayeyJod6v60g',
    appId: '1:464819707457:web:a68fdd88c246fc3a2630c0',
    messagingSenderId: '464819707457',
    projectId: 'realtbox-94ff0',
    authDomain: 'realtbox-94ff0.firebaseapp.com',
    storageBucket: 'realtbox-94ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhDYskN01ZZM3fJ1zRlElDfI54XHXpHY',
    appId: '1:464819707457:ios:782434f2254dd3ba2630c0',
    messagingSenderId: '464819707457',
    projectId: 'realtbox-94ff0',
    storageBucket: 'realtbox-94ff0.appspot.com',
    iosBundleId: 'in.axivise.realtbox',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3KD-jvcxedLyFHle2Z65i9J5U2yPBnA',
    appId: '1:464819707457:android:352ac69456044bd52630c0',
    messagingSenderId: '464819707457',
    projectId: 'realtbox-94ff0',
    storageBucket: 'realtbox-94ff0.appspot.com',
  );

}